---
- name: configure vm1
  hosts: vm1
  gather_facts: no
  connection: local
  sudo: yes
  roles:
  # Restore once jails are moved to service{1,2,3}
  # - base-servicehost
  - role: jail
    name: buildbot
    hostname: buildbot.buildbot.net
    ip_address:
    - 'lo0|127.0.0.239'       # localhost, must be first
    - 'lagg0|140.211.10.239'
    - 'vlan0|192.168.80.239'
  - role: jail
    name: docs
    hostname: docs.buildbot.net
    ip_address:
    - 'lagg0|140.211.10.237'
    - 'vlan0|192.168.80.237'
  - role: jail
    name: www
    hostname: www.buildbot.net
    ip_address:
    - 'lagg0|140.211.10.238'
    - 'vlan0|192.168.80.238'
  - role: jail
    name: bslave1
    hostname: bslave1.int.buildbot.net
    ip_address:
      - 'vlan0|192.168.80.226'

# vim:ts=2:sw=2:noai:nosi
