---
- name: configure service2
  hosts: service2
  gather_facts: no
  connection: local
  sudo: yes
  roles:
  - role: jail
    name: nine
    hostname: nine.buildbot.net
    ip_address:
    - 'lagg0|140.211.10.244'
    - 'vlan0|192.168.80.244'
  - role: jail
    name: bot
    hostname: bot.buildbot.net
    ip_address:
    - 'lagg0|140.211.10.242'
    - 'vlan0|192.168.80.242'
  - role: jail
    name: ftp
    hostname: ftp.buildbot.net
    ip_address:
    - 'lagg0|140.211.10.243'
    - 'vlan0|192.168.80.243'
  - role: jail
    name: lists
    hostname: lists.buildbot.net
    ip_address:
    - 'lagg0|140.211.10.241'
    - 'vlan0|192.168.80.241'
  - role: jail
    name: trac
    hostname: trac.buildbot.net
    ip_address:
    - 'lagg0|140.211.10.240'
    - 'vlan0|192.168.80.240'

# vim:ts=2:sw=2:noai:nosi
