# This is a playbook to be run with ansible-pull (the usage will be described
# when a particular cron task is installed).
# To deploy a particular service manually:
# * log into the target host
# * run 'ansible-playbook -i localhost local.yml -K'
---
- include: "load-secrets.yml"

- name: determine local host name
  hosts: all
  gather_facts: yes
  connection: local

  tasks:
  # Use this to create "special" groups that will be used to setup a particular host.
  # We use non-fqdn here so a staging/test setup could work as well.
  - group_by:
      key: "{{ansible_hostname}}"
    changed_when: False

- include: "track-config.yml"
  vars:
    commit_message: "pre-ansible checkin"

# Service hosts and their jails
- include: "host-service1.yml"
- include: "jail-ns1.yml"
- include: "jail-mx.yml"
- include: "jail-syslog.yml"

- include: "host-service2.yml"
- include: "jail-bot.yml"
- include: "jail-docs.yml"
- include: "jail-ftp.yml"
- include: "jail-lists.yml"
- include: "jail-nine.yml"
- include: "jail-trac.yml"
- include: "jail-www.yml"

- include: "host-service3.yml"
- include: "jail-bslave1.yml"
- include: "jail-buildbot.yml"
- include: "jail-mysql.yml"

- include: "host-vm1.yml"
- include: "vm-linux1.yml"

- include: "track-config.yml"
  vars:
    commit_message: "post-ansible checkin"

# vim:ts=2:sw=2:noai:nosi
