- name: install mandatory packages
  apt:
    name: "{{item}}"
    state: present
  with_items: mandatory_packages

- name: install utility packages
  apt:
    name: "{{item}}"
    state: present
  with_items: utility_packages.debian
